urls.py
'''
Created on 01-Sep-2016

@author: jatinbhola6
'''
from django.conf.urls import url
from . import views
app_name='MnCapp'
urlpatterns=[
             url(r'^$',views.index,name='index'),
             url(r'^signin/$',views.SignInView.as_view(),name='signin'),
             url(r'^signup/$',views.SignUpView.as_view(),name='signup'),
             url(r'^success/$',views.SuccessView.as_view(),name='success'),
             url(r'^logout/$', views.log_out, name='logout'),
             url(r'^writememo/$',views.MemoView.as_view(),name='write_memo'),
             url(r'^getMemo/$',views.getMemo,name='getMemo'),
             url(r'^test/$',views.test,name="test")
]

templates/MnCApp/base.html
{% load MnCapp_filter %}
{% load static %}
<html>
	<head>
		<title>Success Page</title>
		<link rel='stylesheet' type='text/css' href="{% static 'MnCApp/succStyle.css'%}">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
		<script src="{% static 'MnCApp/javaS.js' %}"></script>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	</head>	
	<body>
		<div id="banner">
			<img src="{% static 'MnCApp/images/banner.png'%}"> 
		</div>
		<div id='user-info'>
			<span id='welcomeText'>Welcome, {{emp.first_name}} {{emp.last_name}}</span>
			<div class='dropdown'>
				<div class='dropbtn' onclick='myFunc(this)'>
					<div class='bar1'></div>
					<div class='bar2'></div>
					<div class='bar3'></div>
				</div>			
				<div class='dropdown-content' id='myDropdown' >
					<a>Designation: {{ desigs|key:emp.designation }}</a>
					<a>Department: {{ deptts|key:emp.department }}</a>
					<a>Employee UID(use this to login): {{emp.emp_uid}}</a>
					<a href="{%url 'MnCapp:logout' %}">Log Out</a>
				</div>
			</div>
		</div>
		<ul class="nav nav-tabs">
  			<li class="active"><a data-toggle="tab" href="#memo">Memo</a></li>
  			<li><a data-toggle="tab" href="#circular" >Circular</a></li>
		</ul>	
		<div class="tab-content">
			<div id="memo" class="tab-pane fade in active">
				<h3>Memos</h3>
  				<ul>
  					{% for memo in memo_list %}
  						<li><a href="#" onclick="display('{{ memo.memo_id }}')" data-toggle="modal" data-target="#myMemo">{{ memo.subject }}</a></li>
  					{% endfor %}
  				</ul>
  				<div class="modal fade" id="myMemo" role="dialog">
					<div class="modal-dialog">
						<div class="modal-content">
							<div class="modal-header">
								<button type=button class="close" data-dismiss="modal">&times;</button>
								<div id="sub" class="modal-title"></div>
							</div>
							<div class="modal-body">
								<div id="sender"></div>
								
								<div id="body"></div>
							</div>
							<div class="modal-footer">
								<span id="time"></span>
							</div>
						</div>
					</div>
				</div>	
			</div>
			<div id="circular" class="tab-pane fade ">
  				<h3>Circular</h3>
				<p>List of circulars recieved</p>
			</div>
		</div>
<!-- <a href="{% url 'MnCapp:write_memo' %}"><button>Compose Memo</button></a>  -->
	</body>
</html>

templates/MnCApp/index.html
{% load static %}
<html>
<head>
<title>Memo and Circular Organizer</title>
<link rel="stylesheet" href="{% static 'MnCApp/indStyle.css' %}" />
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
	<div class="logPanel" data-toggle="modal" data-target="#myModal">
		<button class="logInButton btn-primary btn-lg" id="logIn">Log In</button>
	</div>
	<div id="myModal" class="modal fade" role="dialog">
		<div class="modal-dialog">
			<div class="moal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal">&times;</button>
					<h4><span class="glyphicon glyphicon-log-in"></span> Login</h4>
				</div>
				<div class="modal-body">
					<form role="form" method="POST" action="#">
						<div class="form-group">
							{% csrf_token %}
							{% for field in form.visible_fields %}
								<span class="glyphicon {% cycle 'glyphicon-user' 'glyphicon-eye-open' %}"></span>
								<b>
									{{ field.label_tag }}
								</b> 
							{{ field }}
							{% if field.error %}
								<span class='error'>
									{{ field.error }}
								</span>
							{% endif %}
							{% endfor %}
						</div>
						<button type="submit" class="btn btn-default btn-success btn-block">Log In</button>
					</form>
				</div>
				<div class="modal-footer">
					<button type="submit" class="btn btn-default btn-danger pull-left" data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span> Cancel</button>
          			<p>Not a member? <a href="{% url 'MnCApp:signup' %}">Sign Up</a></p>
				</div>
			</div>
		</div>
	</div>
</body>
</html>

templates/MnCApp/memo_comp.html
<html>
<head>
<title>Write your memo</title>
</head>
<body>
<form action="#" method='post'>
{%csrf_token%}
 {% if form.non_field_errors %}
    <ul>
      {% for error in form.non_field_errors %}
        <li>{{ error }}</li>
      {% endfor %}
    </ul>
  {% endif %}
  <table>
  {% for field in form.visible_fields %}
  <div><td>
      {{ field.label_tag }}</td><td> {{ field }}
    </div></td>
    <td><div id="{{ field.auto_id }}_container"><tr>
    {%if field.error %}<td>{{ field.help_text }}</td>{% endif %}
    <div>
  </div>
  {% endfor %}<tr><td>
  <input type="submit" value='Send Memo'></td></tr>
  </table>
</form></body></html>

templates/MnCApp/signin.html
<html>
<head>
<title>Sign In Form
</title>
</head>
<body>
<h3>Sign In</h3>
<form action="#" method='POST'>
{% csrf_token %}
{% if form.non_field_errors %}
    <ul>
      {% for error in form.non_field_errors %}
        <li><strong>{{ error }}</strong></li>
      {% endfor %}
    </ul>
  {% endif %}
{% for field in form.visible_fields %}
  <div id="{{ field.auto_id }}_container">
    <div>
      {{ field.label_tag }} {{ field }}
    </div>
  </div>
  {% endfor %}
<input type='submit' value='Sign In'>
</form>
<a href="{% url 'MnCapp:signup'%}"><button>New Employee?</button></a>
</body>
</html>

templates/MnCApp/signup.html
<html>
<head>
<title>Sign Up Form</title>
</head>
<body>
<h3>Sign Up Form</h3>
<form action="#" method='POST'>
{%csrf_token%}
 {% if form.non_field_errors %}
    <ul>
      {% for error in form.non_field_errors %}
        <li>{{ error }}</li>
      {% endfor %}
    </ul>
  {% endif %}
  {% for field in form.visible_fields %}
  <div id="{{ field.auto_id }}_container">
    {%if field.error %}{{ field.help_text }}{% endif %}
    <div>
      {{ field.label_tag }} {{ field }}
    </div>
    <div id="{{ field.auto_id }}_errors">
      {{ field.errors }}
    </div>
  </div>
  {% endfor %}
<input type='submit' value='Sign Up'>
</form>
</body>
</html>

templates/MnCApp/success.html
{% load MnCapp_filter %}
{% load static %}
<html>
<head>
<title>Success Page</title>
<link rel='stylesheet' type='text/css' href="{% static 'MnCApp/succStyle.css'%}">
<script src="{% static 'MnCApp/javaS.js' %}"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
</head>
<body>
<div id="banner">
<img src="{% static 'MnCApp/images/banner.png'%}"> 
</div>
<div id='user-info'>
<a id='welcomeText'>Welcome, {{emp.first_name}} {{emp.last_name}}</a>
<div class='dropdown'>
<div class='dropbtn' onclick='myFunc(this)'>
<div class='bar1'></div>
<div class='bar2'></div>
<div class='bar3'></div>
</div>
<div class='dropdown-content' id='myDropdown' >
<a>Designation: {{ desigs|key:emp.designation }}</a>
<a>Department: {{ deptts|key:emp.department }}</a>
<a>Employee UID(use this to login): {{emp.emp_uid}}</a>
<a href="{%url 'MnCapp:logout' %}">Log Out</a>
</div>
</div>
</div>
<ul class="tab">
  <li><a href="#" class="tablinks" onclick="openCity(event, 'Memo')">Memo</a></li>
  <li><a href="#" class="tablinks" onclick="openCity(event, 'Circular')">Circular</a></li>
 </ul>
 <div id="Memo" class="tabcontent">
  <h3>Memos</h3>
  <p>Memo is the capital city of England.</p>
  <ul>
  {% for memo in memo_list %}
  	<li><a href="#" onclick="display('{{ memo.memo_id }}')">{{ memo.subject }}</a></li>
  {% endfor %}
  </ul>
</div>

<div id="Circular" class="tabcontent">
  <h3>Circular</h3>
  <p>Circular is the capital of France.</p>
</div>
<!-- <a href="{% url 'MnCapp:write_memo' %}"><button>Compose Memo</button></a>  -->
<div class="modal" id="myModal">
<div class="modal-content">
<span class="close" title="Close" onclick="document.getElementById('myModal').style.display='none'">&times;</span>
<div id="sub"> Subject:</div>
<div id="sender">From: </div>
<div id="body">
<span id="time"></span>
<p id="body"></p>
</div>
</div>
</div>
</body>
</html>